import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NotificationBell } from "./NotificationBell";
import { AuthContext } from "../context/AuthContext";

const api = vi.hoisted(() => ({ getNotifications: vi.fn(), getUnreadNotificationCount: vi.fn(), markNotificationRead: vi.fn(), markAllNotificationsRead: vi.fn() }));
const call = vi.hoisted(() => vi.fn((fn) => fn("token")));
vi.mock("../services/api", () => api);
vi.mock("../hooks/useApi", () => ({ useApi: () => call }));
const unread = { id: "one", type: "registration_approved", title: "Registration approved", message: "Your registration was approved.", is_read: false, created_at: "2030-01-01T10:00:00Z" };
const read = { id: "two", type: "registration_request_submitted", title: "Request submitted", message: "Your request is awaiting review.", is_read: true, created_at: "2030-01-01T09:00:00Z" };
function renderBell(role = "attendee") { return render(<AuthContext.Provider value={{ profile: { role } }}><MemoryRouter initialEntries={["/"]}><Routes><Route path="/admin/registration-requests" element={<p>Approval queue</p>} /><Route path="*" element={<><NotificationBell /><p>Current page</p></>} /></Routes></MemoryRouter></AuthContext.Provider>); }
afterEach(cleanup);
beforeEach(() => { call.mockClear(); Object.values(api).forEach((mock) => mock.mockReset()); api.getUnreadNotificationCount.mockResolvedValue({ unread_count: 1 }); api.getNotifications.mockResolvedValue([unread, read]); api.markNotificationRead.mockResolvedValue({ ...unread, is_read: true }); api.markAllNotificationsRead.mockResolvedValue(null); });
describe("NotificationBell", () => {
  it("shows the accessible bell and a badge only when unread notifications exist", async () => { renderBell(); const bell = screen.getByRole("button", { name: /notifications/i }); await waitFor(() => expect(bell).toHaveAccessibleName("Notifications, 1 unread")); expect(screen.getByText("1")).toBeInTheDocument(); cleanup(); api.getUnreadNotificationCount.mockResolvedValue({ unread_count: 0 }); renderBell(); await waitFor(() => expect(screen.getByRole("button", { name: "Notifications" })).toBeInTheDocument()); expect(screen.queryByText("0")).not.toBeInTheDocument(); });
  it("loads title, message, and readable unread state when opened", async () => { renderBell(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); expect(await screen.findByText("Registration approved")).toBeInTheDocument(); expect(screen.getByText("Your registration was approved.")).toBeInTheDocument(); expect(screen.getByText("Unread")).toBeInTheDocument(); expect(screen.getByText("Request submitted").closest("button")).toHaveClass("is-read"); });
  it("marks an unread item read and updates the badge", async () => { renderBell(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); const item = await screen.findByRole("button", { name: /registration approved/i }); fireEvent.click(item); await waitFor(() => expect(api.markNotificationRead).toHaveBeenCalledWith("one", "token")); await waitFor(() => expect(screen.getByRole("button", { name: "Notifications" })).toBeInTheDocument()); });
  it("marks all items read and hides the badge", async () => { renderBell(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); fireEvent.click(await screen.findByRole("button", { name: "Mark all as read" })); await waitFor(() => expect(api.markAllNotificationsRead).toHaveBeenCalledWith("token")); expect(screen.getByRole("button", { name: "Notifications" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Mark all as read" })).not.toBeInTheDocument(); });
  it("renders a compact empty state and a retryable failure without breaking the page", async () => { api.getNotifications.mockResolvedValue([]); api.getUnreadNotificationCount.mockResolvedValue({ unread_count: 0 }); renderBell(); fireEvent.click(screen.getByRole("button", { name: "Notifications" })); expect(await screen.findByText("No notifications yet.")).toBeInTheDocument(); cleanup(); api.getNotifications.mockRejectedValue(new Error("offline")); renderBell(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); expect(await screen.findByText("Notifications could not be loaded.")).toBeInTheDocument(); expect(screen.getByText("Current page")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Retry" })).toBeInTheDocument(); });
  it("closes via Escape and outside click", async () => { renderBell(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); await screen.findByText("Registration approved"); fireEvent.keyDown(document, { key: "Escape" }); expect(screen.queryByText("Registration approved")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); await screen.findByText("Registration approved"); fireEvent.mouseDown(document.body); expect(screen.queryByText("Registration approved")).not.toBeInTheDocument(); });
  it("uses the same component for admin and sends new requests to the approval queue", async () => { api.getNotifications.mockResolvedValue([{ ...unread, type: "new_registration_request", title: "New registration request" }]); renderBell("admin"); expect(await screen.findByRole("button", { name: /notifications/i })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: /notifications/i })); fireEvent.click(await screen.findByRole("button", { name: /new registration request/i })); expect(await screen.findByText("Approval queue")).toBeInTheDocument(); });
});
