import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AdminRegistrationRequestsPage } from "./AdminRegistrationRequestsPage";

const api = vi.hoisted(() => ({ getAdminRegistrationRequests: vi.fn(), approveRegistrationRequest: vi.fn(), rejectRegistrationRequest: vi.fn() }));
const call = vi.hoisted(() => vi.fn((fn) => fn("token")));
vi.mock("../services/api", () => api);
vi.mock("../hooks/useApi", () => ({ useApi: () => call }));
const pending = { registration_id: "pending-1", attendee_name: "Amina Khan", attendee_email: "amina@example.test", event_title: "Community Forum", event_starts_at: "2030-01-02T10:00:00Z", created_at: "2030-01-01T09:00:00Z", status: "pending" };
const approved = { ...pending, registration_id: "approved-1", status: "approved" };
const rejected = { ...pending, registration_id: "rejected-1", status: "rejected" };
const cancelled = { ...pending, registration_id: "cancelled-1", status: "cancelled" };
afterEach(cleanup);
beforeEach(() => { call.mockClear(); Object.values(api).forEach((mock) => mock.mockReset()); api.getAdminRegistrationRequests.mockImplementation(({ status }) => Promise.resolve(({ pending: [pending], approved: [approved], rejected: [rejected], cancelled: [cancelled] })[status])); api.approveRegistrationRequest.mockResolvedValue({}); api.rejectRegistrationRequest.mockResolvedValue({}); window.confirm = vi.fn(() => true); });
describe("AdminRegistrationRequestsPage", () => {
  it("loads pending by default with attendee, event, status, and decisions", async () => { render(<AdminRegistrationRequestsPage />); expect(await screen.findByText("Amina Khan")).toBeInTheDocument(); expect(screen.getByText("Community Forum")).toBeInTheDocument(); expect(screen.getByText("Pending approval")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Approve" })).toBeEnabled(); expect(screen.getByRole("button", { name: "Reject" })).toBeEnabled(); expect(api.getAdminRegistrationRequests).toHaveBeenCalledWith({ status: "pending" }, "token"); });
  it("filters processed history and hides decisions", async () => { render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("tab", { name: "Approved" })); expect(await screen.findByText("Approved")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Approve" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Reject" })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("tab", { name: "Rejected" })); expect(await screen.findByText("Rejected")).toBeInTheDocument(); fireEvent.click(screen.getByRole("tab", { name: "Cancelled" })); expect(await screen.findByText("Cancelled")).toBeInTheDocument(); });
  it("supports an authoritative all-status view and local search", async () => { render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("tab", { name: "All" })); await screen.findByText("Approved"); expect(api.getAdminRegistrationRequests).toHaveBeenCalledWith({ status: "cancelled" }, "token"); fireEvent.change(screen.getByLabelText("Search requests"), { target: { value: "no match" } }); expect(screen.getByText("No registration requests match this search.")).toBeInTheDocument(); });
  it("approves, disables both actions while processing, and refreshes pending", async () => { let resolveApproval; api.approveRegistrationRequest.mockReturnValue(new Promise((resolve) => { resolveApproval = resolve; })); render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("button", { name: "Approve" })); expect(screen.getByRole("button", { name: "Processing…" })).toBeDisabled(); expect(screen.getByRole("button", { name: "Reject" })).toBeDisabled(); resolveApproval({}); await waitFor(() => expect(api.approveRegistrationRequest).toHaveBeenCalledWith("pending-1", "token")); await screen.findByText("Registration request approved."); });
  it("rejects after confirmation and refreshes pending", async () => { render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("button", { name: "Reject" })); expect(window.confirm).toHaveBeenCalled(); await waitFor(() => expect(api.rejectRegistrationRequest).toHaveBeenCalledWith("pending-1", "token")); expect(await screen.findByText("Registration request rejected.")).toBeInTheDocument(); });
  it("shows useful empty and backend action errors", async () => { api.getAdminRegistrationRequests.mockResolvedValue([]); render(<AdminRegistrationRequestsPage />); expect(await screen.findByText("No registration requests are waiting for review.")).toBeInTheDocument(); cleanup(); api.getAdminRegistrationRequests.mockResolvedValue([pending]); api.approveRegistrationRequest.mockRejectedValue({ code: "event_full" }); render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("button", { name: "Approve" })); expect(await screen.findByText("This event has reached its capacity. This request cannot be approved.")).toBeInTheDocument(); });
  it("explains already processed requests without raw backend messages", async () => { api.approveRegistrationRequest.mockRejectedValue({ code: "request_not_pending", message: "database internal detail" }); render(<AdminRegistrationRequestsPage />); await screen.findByText("Amina Khan"); fireEvent.click(screen.getByRole("button", { name: "Approve" })); expect(await screen.findByText("This request has already been processed.")).toBeInTheDocument(); expect(screen.queryByText("database internal detail")).not.toBeInTheDocument(); });
});
