import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AdminEventsPage } from "./AdminEventsPage";

const api = vi.hoisted(() => ({ getAdminEvents: vi.fn(), createAdminEvent: vi.fn(), updateAdminEvent: vi.fn(), transitionAdminEvent: vi.fn(), deleteAdminEvent: vi.fn() }));
vi.mock("../services/api", () => api);
vi.mock("../hooks/useApi", () => ({ useApi: () => (fn) => fn("token") }));
const draft = { id: "1", title: "Draft", description: "Desc", starts_at: "2030-01-01T10:00:00Z", ends_at: "2030-01-01T12:00:00Z", location: "Hall", capacity: 3, status: "draft" };
const renderPage = () => render(<MemoryRouter><AdminEventsPage /></MemoryRouter>);
afterEach(cleanup);
beforeEach(() => { Object.values(api).forEach((mock) => mock.mockReset()); api.getAdminEvents.mockResolvedValue([draft]); api.createAdminEvent.mockResolvedValue({}); api.updateAdminEvent.mockResolvedValue({}); api.transitionAdminEvent.mockResolvedValue({}); api.deleteAdminEvent.mockResolvedValue({ deleted: true }); window.confirm = vi.fn(() => true); });

describe("AdminEventsPage", () => {
  it("duplicates completed and cancelled events through the normal blank lifecycle create flow", async () => { const completed = { ...draft, id: "2", title: "Completed source", status: "completed" }; const cancelled = { ...draft, id: "3", title: "Cancelled source", status: "cancelled" }; api.getAdminEvents.mockResolvedValue([completed, cancelled]); api.createAdminEvent.mockResolvedValue({ id: "new-event-id" }); renderPage(); await screen.findByText("Completed source"); expect(screen.getAllByRole("button", { name: "Duplicate Event" })).toHaveLength(2); fireEvent.click(screen.getAllByRole("button", { name: "Duplicate Event" })[0]); expect(screen.getByLabelText("Title")).toHaveValue("Completed source"); expect(screen.getByLabelText("Description")).toHaveValue("Desc"); expect(screen.getByLabelText("Location")).toHaveValue("Hall"); expect(screen.getByLabelText("Capacity")).toHaveValue(3); expect(screen.getByLabelText("Status")).toHaveValue(""); expect(screen.getByLabelText("Start date and time")).toHaveValue(""); expect(screen.getByLabelText("End date and time")).toHaveValue(""); fireEvent.change(screen.getByLabelText("Start date and time"), { target: { value: "2031-01-01T10:00" } }); fireEvent.change(screen.getByLabelText("End date and time"), { target: { value: "2031-01-01T12:00" } }); fireEvent.change(screen.getByLabelText("Status"), { target: { value: "draft" } }); fireEvent.click(screen.getByRole("button", { name: "Create event" })); await waitFor(() => expect(api.createAdminEvent).toHaveBeenCalledWith(expect.objectContaining({ title: "Completed source", status: "draft" }), "token")); expect(completed).toMatchObject({ id: "2", status: "completed", starts_at: "2030-01-01T10:00:00Z", ends_at: "2030-01-01T12:00:00Z" }); expect(api.updateAdminEvent).not.toHaveBeenCalled(); });
  it("requires explicit status and end time for new events", async () => { renderPage(); await screen.findByText("Draft"); expect(screen.getByLabelText("Status")).toHaveValue(""); expect(screen.getByLabelText("End date and time")).toHaveValue(""); fireEvent.click(screen.getByRole("button", { name: "Create event" })); expect(screen.getByText("Complete all required fields; capacity must be a positive whole number.")).toBeInTheDocument(); });
  it("keeps edit and lifecycle controls working", async () => { renderPage(); await screen.findByText("Draft"); fireEvent.click(screen.getByRole("button", { name: "Edit" })); expect(screen.getByLabelText("Title")).toHaveValue("Draft"); fireEvent.click(screen.getByRole("button", { name: "Save changes" })); await waitFor(() => expect(api.updateAdminEvent).toHaveBeenCalled()); fireEvent.click(screen.getByRole("button", { name: "Publish" })); await waitFor(() => expect(api.transitionAdminEvent).toHaveBeenCalledWith("1", "published", "token")); });
  it("shows Delete for every lifecycle state", async () => { api.getAdminEvents.mockResolvedValue([draft, { ...draft, id: "2", title: "Published", status: "published" }, { ...draft, id: "3", title: "Completed", status: "completed" }, { ...draft, id: "4", title: "Cancelled", status: "cancelled" }]); renderPage(); await screen.findByText("Cancelled"); expect(screen.getAllByRole("button", { name: "Delete" })).toHaveLength(4); });
  it("requires strong confirmation, warns for published events, and refreshes after deletion", async () => { const published = { ...draft, id: "2", title: "Published", status: "published" }; api.getAdminEvents.mockImplementation(() => Promise.resolve(api.deleteAdminEvent.mock.calls.length ? [] : [published])); renderPage(); await screen.findByText("Published"); window.confirm.mockReturnValueOnce(false); fireEvent.click(screen.getByRole("button", { name: "Delete" })); expect(api.deleteAdminEvent).not.toHaveBeenCalled(); expect(window.confirm).toHaveBeenCalledWith(expect.stringContaining("currently published")); fireEvent.click(screen.getByRole("button", { name: "Delete" })); await waitFor(() => expect(api.deleteAdminEvent).toHaveBeenCalledWith("2", "token")); await waitFor(() => expect(screen.queryByRole("heading", { name: "Published" })).not.toBeInTheDocument()); });
  it("shows professional backend deletion failures", async () => { api.deleteAdminEvent.mockRejectedValue(new Error("This event could not be deleted.")); renderPage(); await screen.findByText("Draft"); fireEvent.click(screen.getByRole("button", { name: "Delete" })); expect((await screen.findAllByText("This event could not be deleted.")).length).toBe(1); });
  it("renders retrieval errors", async () => { api.getAdminEvents.mockRejectedValue(new Error("Admin required")); renderPage(); expect(await screen.findByText("Admin required")).toBeInTheDocument(); });
});
