import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AdminEventsPage } from "./AdminEventsPage";
const api=vi.hoisted(()=>({getAdminEvents:vi.fn(),createAdminEvent:vi.fn(),updateAdminEvent:vi.fn(),transitionAdminEvent:vi.fn()}));
vi.mock("../services/api",()=>api);vi.mock("../hooks/useApi",()=>({useApi:()=>fn=>fn("token")}));
afterEach(cleanup);
beforeEach(()=>{Object.values(api).forEach(x=>x.mockReset());api.getAdminEvents.mockResolvedValue([{id:"1",title:"Draft",description:"Desc",starts_at:"2030-01-01T10:00:00Z",location:"Hall",capacity:3,status:"draft"}]);api.createAdminEvent.mockResolvedValue({});api.updateAdminEvent.mockResolvedValue({});api.transitionAdminEvent.mockResolvedValue({});window.confirm=vi.fn(()=>true)});
describe("AdminEventsPage",()=>{it("renders, validates, edits and publishes through API",async()=>{render(<MemoryRouter><AdminEventsPage/></MemoryRouter>);await screen.findByText("Draft");fireEvent.click(screen.getByRole("button",{name:"Edit"}));await screen.findByRole("button",{name:"Save changes"});expect(screen.getByLabelText("Title")).toHaveValue("Draft");fireEvent.click(screen.getByRole("button",{name:"Save changes"}));await waitFor(()=>expect(api.updateAdminEvent).toHaveBeenCalled());const updatePayload=api.updateAdminEvent.mock.calls[0][1];expect(Object.keys(updatePayload).sort()).toEqual(["capacity","description","location","starts_at","title"]);expect(updatePayload).toMatchObject({title:"Draft",description:"Desc",location:"Hall",capacity:3});await screen.findByText("Draft");fireEvent.click(screen.getByRole("button",{name:"Publish"}));await waitFor(()=>expect(api.transitionAdminEvent).toHaveBeenCalledWith("1","published","token"));});it("renders backend errors",async()=>{api.getAdminEvents.mockRejectedValue(new Error("Admin required"));render(<MemoryRouter><AdminEventsPage/></MemoryRouter>);expect((await screen.findAllByText("Admin required")).length).toBeGreaterThan(0)})});
