import { useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { cancelRegistration,getEvent,getMyEventRegistration,registerForEvent } from "../services/api";
import { useApi } from "../hooks/useApi";
import { AsyncState } from "../components/AsyncState";
const fmt=(date)=>new Intl.DateTimeFormat(undefined,{dateStyle:"full",timeStyle:"short"}).format(new Date(date));
const message=(e)=>({duplicate_registration:"Your registration request already exists.",event_full:"This event has reached its capacity.",event_not_eligible:"Registration is no longer available for this event."}[e.code]||e.message);
const labels={pending:"Pending Approval",approved:"Registration Approved ✓"};
export function EventDetailsPage(){const {eventId}=useParams(),call=useApi(),[event,setEvent]=useState(null),[registration,setRegistration]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const load=()=>{setLoading(true);Promise.all([call(t=>getEvent(eventId,t)),call(t=>getMyEventRegistration(eventId,t))]).then(([e,r])=>{setEvent(e);setRegistration(r?.status?r:null)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[eventId]);const register=async()=>{setBusy(true);setNotice("");try{await call(t=>registerForEvent(eventId,t));setNotice("Your registration request has been sent for approval.");load()}catch(e){setNotice(message(e))}finally{setBusy(false)}};const cancel=async()=>{setBusy(true);try{await call(t=>cancelRegistration(registration.registration_id,t));setNotice(registration.status==="pending"?"Your registration request was withdrawn.":"Your registration was cancelled.");load()}catch(e){setNotice(message(e))}finally{setBusy(false)}};return <AsyncState loading={loading} error={error}><Link className="back-link" to="/events">← All events</Link>{event&&<article className="event-detail"><p className="eyebrow">Published event</p><h1>{event.title}</h1><p className="lead">{event.description}</p><div className="detail-grid"><div><span>When</span><strong>{fmt(event.starts_at)}</strong></div><div><span>Location</span><strong>{event.location}</strong></div><div><span>Availability</span><strong>{event.remaining_availability} of {event.capacity} places remaining</strong></div></div>{notice&&<p className="message message--success" role="alert">{notice}</p>}{registration?<div className={`registration-state ${registration.status}`}><strong>{labels[registration.status]}</strong><p>{registration.status==="pending"?"Your registration request has been sent to the event administrator.":"You are officially registered for this event."}</p><button className="button button--secondary" disabled={busy} onClick={cancel}>{busy?"Updating…":registration.status==="pending"?"Withdraw Request":"Cancel Registration"}</button></div>:<button className="button" disabled={busy||!event.remaining_availability} onClick={register}>{busy?"Registering…":event.remaining_availability?"Register now":"Event full"}</button>}</article>}</AsyncState>}
